"""add_extraction_jobs_table

Revision ID: ac6e5a8b084b
Revises: 558d2a037e3f
Create Date: 2025-06-25 02:10:45.420919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6e5a8b084b'
down_revision: Union[str, None] = '558d2a037e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
