"""add_extraction_jobs_table

Revision ID: e00c7946a297
Revises: ac6e5a8b084b
Create Date: 2025-06-25 02:22:47.529134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00c7946a297'
down_revision: Union[str, None] = 'ac6e5a8b084b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
